### ISSUE TITLE
It's missing an example script

### ISSUE THREAD

**Issue by almendieta** [mazinsw/nsMySQL#2]
Hi. It's missing a usage example of this plugin, ideally a script detailing how to use it. Have an example of issue I've found trying to use it:
SELECT ID FROM CLIENTS WHERE ID='" $R3 "'"
This query won't work!

**Comment by mazinsw** [comment]
Try using single quotes around or escape  double quotes

**Comment by almendieta** [comment]
Thanks a lot for your answer Francimar! I'm double quoted a simple query
(and each parameter in the call) and it seems work correctly, because the
logfile throws a message: No database selected. How can I select the DB
please? And how can I retrieve the data so can use it in NSIS? Obrigado in
advance for your answer! :)

Al.





-----------------------------------------------------------------------------
Si vas a reenviar este mensaje, ten en cuenta lo siguiente:
            1..- Borra la dirección del remitente así como cualquier otra
dirección que aparezca en el cuerpo del mensaje.
            2.- Protege las direcciones de los destinatarios colocando las
mismas en la línea CCO (COPIA OCULTA), de esta forma evitamos los mensajes
SPAM.

**Comment by mazinsw** [comment]
Append `USE my_db;` at beginning of your script to select `my_db` database

You cannot retrieve data using this plugin, it was made for database creation and seeds
